#!/usr/bin/env python
'''
Run the program to build the de-identified data set over a particular directory that contains yob and forum
bin files of the right sizes for the specified k-anonymity values. This assumes that the output files from the earlier
stages of the de-identification pipeline are named in a particular way:
    user/class suppression files (generated by courseSetDeIdentify.py) are named classSuppressSetX{P,R} where X is the
     k-anonymity level and P or R indicated the algorithm used for suppression;

     YoB and Forum generalization files are named yobbinXXk and postbinXXk where XX is the number (in thousands) of the
     minimum bin size;

     The mapping from country code to country or region is named countryGenXXk, where XX is the minimum bin size (in
     thousands) of the bins for the country or region

     The file containing the full suppression set is named fullSuppressXXYYk{P,R} where XX is the bin size for the
     YOB binning, YY is the bin size for forum binning. It is assumed that the country binning will be the same as
     the YoB binning.
'''
import buildDeIdentifiedCSV as csvBuilder
from de_id_functions import dbOpen

bin_size = ['00','05', '10', '15', '20', '25']
k_vals = [3,4,5,6]

cr = dbOpen('year.db')
cr.execute(csvBuilder.build_select_string('source'))
user_course_list = cr.fetchall()

country_base = 'countryGen'

for k in k_vals:
    for s in bin_size:
        class_supp = 'classSuppressSet' + str(k) + 'P'
        country_file = country_base + s + 'k'
        yob_fname = 'yobbin'+ s + 'k'
        fbin_fname = 'postbin' + s + 'k'
        full_suppress = 'fullSuppress' + s + s + str(k) + 'P'
        de_id_fname = 'deIdFile' + s + s + str(k) + 'P.csv'
        csvBuilder.main(user_course_list, de_id_fname, full_suppress,
                                          country_file, yob_fname, fbin_fname)
